### ISSUE TITLE
Uniform.r

### ISSUE THREAD

**Issue by hswhsy** [DSSAT/glue#12]
Hi,
I'm Shinwoo Hyun from Seoul National University.

In Uniform.r, if statement for GLUEFlag==2 doesn't have option for Flag=="G"
I think it should be changed as below

else if (GLUEFlag==2)
{
    if (Flag=="P)
    else if (Flag=="N")
    **else if (Flag=="P")** -> **else if (Flag=="G")**
}

**Comment by fabiooliveira72** [comment]
Hi @hswhsy!

This issue was already fixed.
Thank you.
Fabio Oliveira
