### ISSUE TITLE
missing '/' in OutputProcessing.r

### ISSUE THREAD

**Issue by hswhsy** [DSSAT/glue#3]
OutputProcessing.r makes "C:/DSSAT47/GLWorkEvaluate_output.txt"

 eval(parse(text=paste('write("",file = "',OD,'Evaluate_output.txt")',sep = '')));
should be changed to 
 eval(parse(text=paste('write("",file = "',OD,'/Evaluate_output.txt")',sep = '')));

**Comment by GerritHoogenboom** [comment]
Fixed, thank you!
