### ISSUE TITLE
EvaluateProcessing.r

### ISSUE THREAD

**Issue by Opamelas83** [DSSAT/glue#4]
Hi, 
I'm Michelle Okoma from Cornell University.
After the run of GLUE 1, then, Likelihood calculation is starting.. , I often got this error message:

 in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 21 did not have 65 elements ...
 eval(parse(text = paste("Evaluation<-read.table(\"", DSSATD, "/EvaluateFrame_1.txt\", header=TRUE, comment.char = \"\")", sep = ""))) at IntegratedLikelihoodCalculation1.r#7**

I checked the "EvaluateFrame_1.txt" file and I saw that some data cells have merged
[EvaluateFrame_1.txt](https://github.com/DSSAT/glue/files/6780961/EvaluateFrame_1.txt)

Also, the issue is not fixed. It occurs on most txt files.
Thanks for your help!

**Comment by chporter** [comment]
@Opamelas83 Can you tell us what version of DSSAT you are using?

**Comment by Opamelas83** [comment]
> @Opamelas83 Can you tell us what version of DSSAT you are using?

I use DSSAT 4.7.5.0

**Comment by chporter** [comment]
@Opamelas83 Are you working with cassava? Unfortunately, cassava does not (yet) work with GLUE.

**Comment by Opamelas83** [comment]
Okay, Thanks

**Comment by Opamelas83** [comment]
Please, Maybe we can try to fix the problem for cassava. I'm looking for tool for estimate genotype parameters of 60 cassava cultivars from 10 locations.

**Comment by lpmorenoc** [comment]
@Opamelas83 have you tried to use Gencalc? Recently I modified the rules for cassava and it should be working ok. I will send you a message with the update file.
> Please, Maybe we can try to fix the problem for cassava. I'm looking for tool for estimate genotype parameters of 60 cassava cultivars from 10 locations.

**Comment by Opamelas83** [comment]
Not recently. I'm going to do that.
Thanks

**Comment by Opamelas83** [comment]
> @Opamelas83 have you tried to use Gencalc? Recently I modified the rules for cassava and it should be working ok. I will send you a message with the update file.
> 
> > Please, Maybe we can try to fix the problem for cassava. I'm looking for tool for estimate genotype parameters of 60 cassava cultivars from 10 locations.
